# compose for nginx
version: "3.9"

services: 
    jekyll:
        build:
            context: ..
            dockerfile: docker/jekyll.Dockerfile
        image: ghcr.io/thinkland/jekyll1:latest
        ports:
            - "8080:80"
        environment: 
            - NGINX_PORT=80
