apiVersion: apps/v1
kind: Deployment
metadata:
  name: ministake2
spec:
  selector:
    matchLabels:
      app: ministake2
  template:
    metadata:
      labels:
        app: ministake2
    spec:
      containers:
      - name: ministake2
        image: jekyll1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred


