# github workflow deploy to netcup
# version: 2021-06-05 13:00:00

name: Build and Deploy to Netcup

on: [push]

env:
  REGISTRY: ghcr.io
  GH_USER: ${{ github.actor }}
  REG_PASS: ${{ secrets.GHCR_PAT_TOKEN }}
  IMAGE_NAME: jekyll1
  IMAGE_TAG: latest   # TODO

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Docker login
    - name: Log in to GitHub Docker Registry
      run: |-
        echo $REG_PASS | docker login $REGISTRY -u $GH_USER --password-stdin

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$REGISTRY/$GH_USER/$IMAGE_NAME:$IMAGE_TAG" \
          --file docker/jekyll.Dockerfile \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$REGISTRY/$GH_USER/$IMAGE_NAME:$IMAGE_TAG"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the Netcup cluster
    # before with: kubectl rollout status deployment/$DEPLOYMENT_NAME
    # TODO:    ./kustomize build | kubectl apply -f -
    - name: Deploy
      run: |-
        cd k8s/prod
        pwd
        cp ../../kustomize .
        ls -la
        ./kustomize edit set image jekyll1=$REGISTRY/$GH_USER/$IMAGE_NAME:$IMAGE_TAG
        ./kustomize build
        kubectl get all -o wide
